In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv(r"C:\Users\JEC\Desktop\6th Semester\training_set_rel3.tsv", sep='\t', on_bad_lines='skip', encoding='ISO-8859-1')
df

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,rater3_domain1,domain1_score,rater1_domain2,rater2_domain2,domain2_score,...,rater2_trait3,rater2_trait4,rater2_trait5,rater2_trait6,rater3_trait1,rater3_trait2,rater3_trait3,rater3_trait4,rater3_trait5,rater3_trait6
0,1,1,"Dear local newspaper, I think effects computer...",4,4,NaN,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",5,4,NaN,9,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",4,3,NaN,7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",5,5,NaN,10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,"Dear @LOCATION1, I know having computers has a...",4,4,NaN,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12971,21626,8,In most stories mothers and daughters are eit...,17,18,NaN,35,NaN,NaN,NaN,...,4.0,4.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
12972,21628,8,I never understood the meaning laughter is th...,15,17,NaN,32,NaN,NaN,NaN,...,4.0,4.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
12973,21629,8,"When you laugh, is @CAPS5 out of habit, or is ...",20,26,40.0,40,NaN,NaN,NaN,...,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,4.0
12974,21630,8,Trippin' on fen...,20,20,NaN,40,NaN,NaN,NaN,...,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
12975,21633,8,Many people believe that laughter can improve...,20,20,NaN,40,NaN,NaN,NaN,...,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.dropna(axis=1,inplace=True)
df.drop(columns=['rater1_domain1','rater2_domain1'],inplace=True,axis=1)
df.head()

,essay_id,essay_set,essay,domain1_score
0,1,1,"Dear local newspaper, I think effects computer...",8
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",9
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",7
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",10
4,5,1,"Dear @LOCATION1, I know having computers has a...",8

# DATA PREPROCESSING

In [4]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize,word_tokenize
from gensim.models import Word2Vec
import re
from sklearn.model_selection import train_test_split

In [5]:
df["essay"][1]

"Dear @CAPS1 @CAPS2, I believe that using computers will benefit us in many ways like talking and becoming friends will others through websites like facebook and mysace. Using computers can help us find coordibates, locations, and able ourselfs to millions of information. Also computers will benefit us by helping with jobs as in planning a house plan and typing a @NUM1 page report for one of our jobs in less than writing it. Now lets go into the wonder world of technology. Using a computer will help us in life by talking or making friends on line. Many people have myspace, facebooks, aim, these all benefit us by having conversations with one another. Many people believe computers are bad but how can you make friends if you can never talk to them? I am very fortunate for having a computer that can help with not only school work but my social life and how I make friends. Computers help us with finding our locations, coordibates and millions of information online. If we didn't go on the internet a lot we wouldn't know how to go onto websites that @MONTH1 help us with locations and coordinates like @LOCATION1. Would you rather use a computer or be in @LOCATION3. When your supposed to be vacationing in @LOCATION2. Million of information is found on the internet. You can as almost every question and a computer will have it. Would you rather easily draw up a house plan on the computers or take @NUM1 hours doing one by hand with ugly erazer marks all over it, you are garrenteed that to find a job with a drawing like that. Also when appling for a job many workers must write very long papers like a @NUM3 word essay on why this job fits you the most, and many people I know don't like writing @NUM3 words non-stopp for hours when it could take them I hav an a computer. That is why computers we needed a lot now adays. I hope this essay has impacted your descion on computers because they are great machines to work with. The other day I showed my mom how to use a computer and she said it was the greatest invention sense sliced bread! Now go out and buy a computer to help you chat online with friends, find locations and millions of information on one click of the button and help your self with getting a job with neat, prepared, printed work that your boss will love."

In [6]:
df.head(1)

,essay_id,essay_set,essay,domain1_score
0,1,1,"Dear local newspaper, I think effects computer...",8

In [7]:
# `Removing stopword
nltk.download('stopwords')

[nltk_data] Error loading stopwords: <urlopen error [WinError 10061]
[nltk_data]     No connection could be made because the target machine
[nltk_data]     actively refused it>

False

In [8]:
words=set(stopwords.words("english"))
def remove_stopwords(essay):
  wtoken= word_tokenize(essay)
  filter=[]
  for w in wtoken:
    if w not in words:
      filter.append(w)
      return ' '.join(filter)

df['clean_essay'] = df['essay'].apply(lambda x:remove_stopwords(x))  
df.head()

,essay_id,essay_set,essay,domain1_score,clean_essay
0,1,1,"Dear local newspaper, I think effects computer...",8,Dear
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",9,Dear
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",7,Dear
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",10,Dear
4,5,1,"Dear @LOCATION1, I know having computers has a...",8,Dear

In [9]:
def remove_puncs(essay):
    essay = re.sub("[^A-Za-z ]","",essay)
    return essay

df['clean_essay'] = df['essay'].apply(lambda x:remove_puncs(x))

In [10]:
df.head()

,essay_id,essay_set,essay,domain1_score,clean_essay
0,1,1,"Dear local newspaper, I think effects computer...",8,Dear local newspaper I think effects computers...
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",9,Dear CAPS CAPS I believe that using computers ...
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",7,Dear CAPS CAPS CAPS More and more people use c...
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",10,Dear Local Newspaper CAPS I have found that ma...
4,5,1,"Dear @LOCATION1, I know having computers has a...",8,Dear LOCATION I know having computers has a po...

In [11]:
def clean_essay(essay):
    x=[]
    for i in essay.split():
        if i.startswith("@"):
            continue
        else:
            x.append(i)
    return ' '.join(x)

df['clean_essay'] = df['essay'].apply(lambda x:clean_essay(x))

df.head()

,essay_id,essay_set,essay,domain1_score,clean_essay
0,1,1,"Dear local newspaper, I think effects computer...",8,"Dear local newspaper, I think effects computer..."
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",9,Dear I believe that using computers will benef...
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",7,"Dear, More and more people use computers, but ..."
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",10,"Dear Local Newspaper, I have found that many e..."
4,5,1,"Dear @LOCATION1, I know having computers has a...",8,Dear I know having computers has a positive ef...

In [12]:
df["essay"][1]

"Dear @CAPS1 @CAPS2, I believe that using computers will benefit us in many ways like talking and becoming friends will others through websites like facebook and mysace. Using computers can help us find coordibates, locations, and able ourselfs to millions of information. Also computers will benefit us by helping with jobs as in planning a house plan and typing a @NUM1 page report for one of our jobs in less than writing it. Now lets go into the wonder world of technology. Using a computer will help us in life by talking or making friends on line. Many people have myspace, facebooks, aim, these all benefit us by having conversations with one another. Many people believe computers are bad but how can you make friends if you can never talk to them? I am very fortunate for having a computer that can help with not only school work but my social life and how I make friends. Computers help us with finding our locations, coordibates and millions of information online. If we didn't go on the internet a lot we wouldn't know how to go onto websites that @MONTH1 help us with locations and coordinates like @LOCATION1. Would you rather use a computer or be in @LOCATION3. When your supposed to be vacationing in @LOCATION2. Million of information is found on the internet. You can as almost every question and a computer will have it. Would you rather easily draw up a house plan on the computers or take @NUM1 hours doing one by hand with ugly erazer marks all over it, you are garrenteed that to find a job with a drawing like that. Also when appling for a job many workers must write very long papers like a @NUM3 word essay on why this job fits you the most, and many people I know don't like writing @NUM3 words non-stopp for hours when it could take them I hav an a computer. That is why computers we needed a lot now adays. I hope this essay has impacted your descion on computers because they are great machines to work with. The other day I showed my mom how to use a computer and she said it was the greatest invention sense sliced bread! Now go out and buy a computer to help you chat online with friends, find locations and millions of information on one click of the button and help your self with getting a job with neat, prepared, printed work that your boss will love."

In [13]:
def sent2word(x):
    x=re.sub("[^A-Za-z0-9]"," ",x)
    words=nltk.word_tokenize(x)
    return words

def essay2word(essay):
    essay = essay.strip()
    tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
    raw = tokenizer.tokenize(essay)
    final_words=[]
    for i in raw:
        if(len(i)>0):
            final_words.append(sent2word(i))
    return final_words
        

def noOfWords(essay):
    count=0
    for i in essay2word(essay):
        count=count+len(i)
    return count

def noOfChar(essay):
    count=0
    for i in essay2word(essay):
        for j in i:
            count=count+len(j)
    return count

def avg_word_len(essay):
    return noOfChar(essay)/noOfWords(essay)

def noOfSent(essay):
    return len(essay2word(essay))

def count_pos(essay):
    sentences = essay2word(essay)
    noun_count=0
    adj_count=0
    verb_count=0
    adverb_count=0
    for i in sentences:
        pos_sentence = nltk.pos_tag(i)
        for j in pos_sentence:
            pos_tag = j[1]
            if(pos_tag[0]=='N'):
                noun_count+=1
            elif(pos_tag[0]=='V'):
                verb_count+=1
            elif(pos_tag[0]=='J'):
                adj_count+=1
            elif(pos_tag[0]=='R'):
                adverb_count+=1
    return noun_count,verb_count,adj_count,adverb_count

data = open(r'C:\Users\JEC\Desktop\6th Semester\big.txt').read()
words = re.findall('[a-z]+', data.lower())

def check_spell_error(essay):
    essay=essay.lower()
    new_essay = re.sub("[^A-Za-z0-9]"," ",essay)
    new_essay = re.sub("[0-9]","",new_essay)
    count=0
    all_words = new_essay.split()
    for i in all_words:
        if i not in words:
            count+=1
    return count
    
def avg_sent_len(essay):
    return noOfWords(essay)/noOfSent(essay)

In [14]:
df

,essay_id,essay_set,essay,domain1_score,clean_essay
0,1,1,"Dear local newspaper, I think effects computer...",8,"Dear local newspaper, I think effects computer..."
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",9,Dear I believe that using computers will benef...
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",7,"Dear, More and more people use computers, but ..."
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",10,"Dear Local Newspaper, I have found that many e..."
4,5,1,"Dear @LOCATION1, I know having computers has a...",8,Dear I know having computers has a positive ef...
...,...,...,...,...,...
12971,21626,8,In most stories mothers and daughters are eit...,35,In most stories mothers and daughters are eith...
12972,21628,8,I never understood the meaning laughter is th...,32,I never understood the meaning laughter is the...
12973,21629,8,"When you laugh, is @CAPS5 out of habit, or is ...",40,"When you laugh, is out of habit, or is cause? ..."
12974,21630,8,Trippin' on fen...,40,"Trippin' on fences I am years young, and in th..."
12975,21633,8,Many people believe that laughter can improve...,40,Many people believe that laughter can improve ...

In [15]:
dat=df.copy()

In [16]:
dat["wordcount"]= dat["essay"].apply(noOfWords)
dat["charcount"]= dat["essay"].apply(noOfChar)
dat["avglen"]= dat["essay"].apply(avg_word_len)
dat["sentencecount"]= dat["essay"].apply(noOfSent)
dat["spellerror"]= dat["essay"].apply(check_spell_error)
dat["avg_sent"]=dat["essay"].apply(avg_sent_len)
dat['noun_count'], dat['adj_count'], dat['verb_count'], dat['adv_count'] = zip(*dat['essay'].map(count_pos))

In [17]:
dat.to_csv("processed_data.csv")

In [18]:
dat

,essay_id,essay_set,essay,domain1_score,clean_essay,wordcount,charcount,avglen,sentencecount,spellerror,avg_sent,noun_count,adj_count,verb_count,adv_count
0,1,1,"Dear local newspaper, I think effects computer...",8,"Dear local newspaper, I think effects computer...",350,1483,4.237143,16,11,21.875000,83,74,18,24
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",9,Dear I believe that using computers will benef...,423,1824,4.312057,20,25,21.150000,107,85,19,19
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",7,"Dear, More and more people use computers, but ...",283,1229,4.342756,14,5,20.214286,82,52,20,16
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",10,"Dear Local Newspaper, I have found that many e...",530,2551,4.813208,27,34,19.629630,178,97,42,29
4,5,1,"Dear @LOCATION1, I know having computers has a...",8,Dear I know having computers has a positive ef...,473,2050,4.334038,30,19,15.766667,114,90,32,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12971,21626,8,In most stories mothers and daughters are eit...,35,In most stories mothers and daughters are eith...,863,3450,3.997683,27,13,31.962963,180,171,48,71
12972,21628,8,I never understood the meaning laughter is th...,32,I never understood the meaning laughter is the...,559,2149,3.844365,35,14,15.971429,135,103,40,55
12973,21629,8,"When you laugh, is @CAPS5 out of habit, or is ...",40,"When you laugh, is out of habit, or is cause? ...",835,3586,4.294611,41,19,20.365854,202,171,41,60
12974,21630,8,Trippin' on fen...,40,"Trippin' on fences I am years young, and in th...",576,2367,4.109375,39,16,14.769231,115,108,40,53
12975,21633,8,Many people believe that laughter can improve...,40,Many people believe that laughter can improve ...,475,1986,4.181053,29,7,16.379310,96,104,43,35